<div class="poli container" style="text-align: justify;">
    <article class="targeta center">
          <h2>POLÍTICA DE PRIVACIDAD</h2>
          <p>&nbsp;</p>
          <p>El presente Política de Privacidad establece los términos en que <a href="http://animecream.com/" target="_blank" rel="nofollow noopener">animecream.com</a> usa y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web. Estamos comprometidos con la seguridad de los datos de sus usuarios. Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios.</p>
          <p><a href="http://animecream.com/" target="_blank" rel="nofollow noopener">animecream.com</a> está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.</p>
          <h3>Cookies</h3>
          <p>Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener información respecto al tráfico web, y también facilita las futuras visitas a una web recurrente. Otra función que tienen las cookies es que con ellas las web pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.</p>
          <p>Nuestro sitio web emplea las cookies para poder identificar las páginas que son visitadas y su frecuencia. Esta información es empleada únicamente para análisis estadístico y después la información se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo las cookies ayudan a proporcionar un mejor servicio de los sitios web, estás no dan acceso a información de su ordenador ni de usted, a menos de que usted así lo quiera y la proporcione directamente, visitas a una web . Usted puede aceptar o negar el uso de cookies, sin embargo la mayoría de navegadores aceptan cookies automáticamente pues sirve para tener un mejor servicio web. También usted puede cambiar la configuración de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios.</p>
          <h4>Google Analytics:</h4>
          <p>Google Analytics es un servicio analítico de web prestado por Google, Inc., una compañía de Delaware cuya oficina principal está en 1600 Amphitheatre Parkway, Mountain View (California), CA 94043, Estados Unidos (“Google”). Google Analytics utiliza “cookies”, que son archivos de texto ubicados en su ordenador, para ayudar al website a analizar el uso que hacen los usuarios del sitio web. La información que genera la cookie acerca de su uso del website (incluyendo su dirección IP) será directamente transmitida y archivada por Google. Google usará esta información por cuenta nuestra con el propósito de seguir la pista de su uso del website, recopilando informes de la actividad del website y prestando otros servicios relacionados con la actividad del website y el uso de Internet. Google podrá transmitir dicha información a terceros cuando así se lo requiera la legislación, o cuando dichos terceros procesen la información por cuenta de Google. Google no asociará su dirección IP con ningún otro dato del que disponga Google. Puede Usted rechazar el tratamiento de los datos o la información rechazando el uso de cookies mediante la selección de la configuración apropiada de su navegador, sin embargo, debe Usted saber que si lo hace puede ser que no pueda usar la plena funcionabilidad de este website. Al utilizar este website Usted consiente el tratamiento datos por parte de Google en la forma y para los fines indicados. Los usuarios pueden acceder a la política de privacidad de la red de contenido en <a href="https://www.google.com/intl/es/policies/privacy/?authuser=0" target="_blank" rel="nofollow noopener">https://www.google.com/intl/es/policies/privacy/</a>.</p>
          <h4>Google Adsense:</h4>
          <p>Google, como proveedor asociado, utiliza cookies para publicar anuncios en este sitio web. Los usuarios pueden inhabilitar el uso de la cookie de DART a través del anuncio de Google y accediendo a la política de privacidad de la red de contenido <a href="https://www.google.com/intl/es/policies/privacy/?authuser=0" target="_blank" rel="nofollow noopener">https://www.google.com/intl/es/policies/privacy/</a> .Google utiliza empresas publicitarias asociadas para publicar anuncios cuando visita nuestro sitio web. Es posible que estas empresas usen la información que obtienen de sus visitas a este y otros sitios web (sin incluir su nombre, dirección, dirección de correo electrónico o número de teléfono) para ofrecerle anuncios sobre productos y servicios que le resulten de interés. Al utilizar este website Usted consiente el tratamiento de datos por parte de Google en la forma y para los fines indicados.</p>
          <p>Asimismo los usuarios pueden inhabilitar la publicidad personalizada para ello deberán Acceder al siguiente enlace: <a href="https://www.google.com/settings/ads?authuser=0" target="_blank" rel="nofollow noopener">https://www.google.com/settings/ads</a></p>
          <p>Si no desean que otros proveedores utilicen cookies para la publicidad personalizada debe acceder a <a href="http://www.aboutads.info/choices/" target="_blank" rel="nofollow noopener">http://www.aboutads.info/choices/</a></p>
          <p>&nbsp;</p>
          <h4>Enlaces a Terceros</h4>
          <p>Este sitio web pudiera contener enlaces a otros sitios que pudieran ser de su interés. Una vez que usted de clic en estos enlaces y abandone nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o privacidad ni de la protección de sus datos en esos otros sitios terceros. Dichos sitios están sujetos a sus propias políticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted está de acuerdo con estas.</p>
          <p><a href="http://animecream.com/" target="_blank" rel="nofollow noopener">animecream.com</a> Se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.</p>
        </div><!-- .entry-content -->
      </article><!-- #post-19 -->

    </div>